### ISSUE TITLE
全编译错误  提示so 无效

### ISSUE THREAD

**Issue by cuke-amuse** [NarutoDing/naruto_apollo_v7#2]
cuke@cuke-X542UNT:~/work/Apollo-local/naruto_apollo_v7$ python3.9 cmake/apollo_build_script.py -p host-linux

Error: Couldn't import few required libraries in buildHelper.py /home/cuke/work/Apollo-local/naruto_apollo_v7/tools/Python-3.9.5/lib/python3.9/lib-dynload/binascii.cpython-39-x86_64-linux-gnu.so: invalid ELF header 
Please use python3 from Main/Tool/python3.x.y QC8 project

**Comment by NarutoDing** [comment]
sorry may be there are some problems with python, please download the code from baidu and replace the python code 
链接：https://pan.baidu.com/s/1WXGYDL3or2NJfqyRQAK8nA 
提取码：t6ij 
--来自百度网盘超级会员V6的分享

**Comment by NarutoDing** [comment]
down load the tools ,dan replace the pyhton code
